#!/usr/bin/env bash
# tandem — install/uninstall the status line integration for the current user.
#
# Claude Code has no mechanism for a plugin to provide the main status line
# (a plugin's settings.json only supports `agent` and `subagentStatusLine`),
# so this script does, with the user's consent, what the platform cannot:
#
#   1. writes a small SHIM to ~/.claude/tandem-statusline.sh that re-resolves
#      the plugin's real statusline.sh on every render — first $TANDEM_STATUSLINE_SCRIPT,
#      then the installed plugin (whose cache path changes on every update),
#      then the path this installer ran from, and finally a minimal built-in
#      render so the status line never dies if tandem is uninstalled;
#   2. merges a `statusLine` entry pointing at the shim into ~/.claude/settings.json
#      (atomically, with a backup, and never clobbering a status line that
#      isn't ours unless --force).
#
# usage: statusline-install.sh [install|uninstall|status] [--force]
# exit codes: 0 ok · 1 failure · 2 refused (foreign statusLine, use --force)
#             3 missing dependency · 64 usage error

set -euo pipefail
SCRIPT_DIR="$(CDPATH='' cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=_common.sh
. "$SCRIPT_DIR/_common.sh"

PLUGIN_ROOT="$(CDPATH='' cd -- "$SCRIPT_DIR/.." && pwd)"
CLAUDE_DIR="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
SHIM="$CLAUDE_DIR/tandem-statusline.sh"
SETTINGS="$CLAUDE_DIR/settings.json"

ACTION="${1:-install}"
FORCE=0
[ "${2:-}" = "--force" ] && FORCE=1

need_jq

is_ours() {
  # true when settings.json's statusLine points at our shim
  [ -f "$SETTINGS" ] || return 1
  jq -e '.statusLine.command // "" | test("tandem-statusline")' "$SETTINGS" >/dev/null 2>&1
}

write_shim() {
  mkdir -p "$CLAUDE_DIR"
  local tmp
  tmp="$(mktemp "$CLAUDE_DIR/.tandem-statusline.XXXXXX")"
  {
    printf '#!/usr/bin/env bash\n'
    printf '# tandem status line shim — generated by statusline-install.sh; do not edit.\n'
    printf 'BAKED=%q\n' "$PLUGIN_ROOT/scripts/statusline.sh"
    cat <<'SHIM_EOF'
set -uo pipefail

resolve() {
  if [ -n "${TANDEM_STATUSLINE_SCRIPT:-}" ] && [ -f "$TANDEM_STATUSLINE_SCRIPT" ]; then
    printf '%s' "$TANDEM_STATUSLINE_SCRIPT"; return
  fi
  local reg="${CLAUDE_CONFIG_DIR:-$HOME/.claude}/plugins/installed_plugins.json" p
  if command -v jq >/dev/null 2>&1 && [ -f "$reg" ]; then
    while IFS= read -r p; do
      if [ -n "$p" ] && [ -f "$p/scripts/statusline.sh" ]; then
        printf '%s' "$p/scripts/statusline.sh"; return
      fi
    done <<EOF
$(jq -r '.plugins // {} | to_entries[] | select(.key | startswith("tandem@"))
         | .value[].installPath // empty' "$reg" 2>/dev/null)
EOF
  fi
  [ -f "$BAKED" ] && { printf '%s' "$BAKED"; return; }
  printf ''
}

SCRIPT="$(resolve)"
if [ -n "$SCRIPT" ]; then
  exec bash "$SCRIPT"
fi

# tandem is gone — render a minimal line instead of erroring out.
command -v jq >/dev/null 2>&1 || exit 0
jq -r '"◈ " + (.model.display_name // .model.id // "?")
       + (if (.context_window.used_percentage // null) != null
          then " · ctx " + (.context_window.used_percentage | floor | tostring) + "%"
          else "" end)' 2>/dev/null || true
SHIM_EOF
  } >"$tmp"
  chmod +x "$tmp"
  mv -f "$tmp" "$SHIM"
}

settings_set() {
  mkdir -p "$CLAUDE_DIR"
  [ -f "$SETTINGS" ] || printf '{}\n' >"$SETTINGS"
  jq -e . "$SETTINGS" >/dev/null 2>&1 \
    || die "$SETTINGS is not valid JSON — fix it by hand first (nothing was changed)" 1
  cp "$SETTINGS" "$SETTINGS.tandem-backup"
  local tmp
  tmp="$(mktemp "$CLAUDE_DIR/.settings.XXXXXX")"
  jq --arg cmd "$SHIM" \
    '.statusLine = {type: "command", command: $cmd, refreshInterval: 2}' \
    "$SETTINGS" >"$tmp"
  mv -f "$tmp" "$SETTINGS"
}

case "$ACTION" in
  install)
    if [ -f "$SETTINGS" ] && jq -e '.statusLine' "$SETTINGS" >/dev/null 2>&1 \
       && ! is_ours && [ "$FORCE" -ne 1 ]; then
      printf 'tandem: %s already has a statusLine that is not tandem'\''s:\n' "$SETTINGS" >&2
      jq '.statusLine' "$SETTINGS" >&2
      printf 'tandem: re-run with --force to replace it (a backup is kept).\n' >&2
      exit 2
    fi
    write_shim
    settings_set
    printf 'tandem: status line installed.\n'
    printf '  shim:     %s\n' "$SHIM"
    printf '  resolves: %s\n' "$PLUGIN_ROOT/scripts/statusline.sh"
    printf '  settings: %s (backup: %s)\n' "$SETTINGS" "$SETTINGS.tandem-backup"
    printf 'Restart Claude Code (or open a new session) to see it.\n'
    ;;
  uninstall)
    if is_ours; then
      cp "$SETTINGS" "$SETTINGS.tandem-backup"
      tmp="$(mktemp "$CLAUDE_DIR/.settings.XXXXXX")"
      jq 'del(.statusLine)' "$SETTINGS" >"$tmp"
      mv -f "$tmp" "$SETTINGS"
      printf 'tandem: statusLine entry removed from %s.\n' "$SETTINGS"
    else
      printf 'tandem: settings statusLine is not tandem'\''s — left untouched.\n'
    fi
    if [ -f "$SHIM" ]; then
      rm -f "$SHIM"
      printf 'tandem: shim removed: %s\n' "$SHIM"
    fi
    ;;
  status)
    if [ -f "$SHIM" ]; then printf '  shim:     present (%s)\n' "$SHIM"
    else printf '  shim:     not installed\n'; fi
    if is_ours; then printf '  settings: statusLine -> tandem shim\n'
    elif [ -f "$SETTINGS" ] && jq -e '.statusLine' "$SETTINGS" >/dev/null 2>&1; then
      printf '  settings: statusLine present but NOT tandem'\''s\n'
    else printf '  settings: no statusLine configured\n'; fi
    printf '  source:   %s\n' "$PLUGIN_ROOT/scripts/statusline.sh"
    ;;
  *)
    die "usage: statusline-install.sh [install|uninstall|status] [--force]" 64
    ;;
esac
